const form = document.querySelector('#order-form');
const status = document.querySelector('#form-status');
const checks = [...form.querySelectorAll('[name="items"]')];
const menu = document.querySelector('.menu-toggle');
const nav = document.querySelector('#navigation');
menu.addEventListener('click', () => {const open=menu.getAttribute('aria-expanded')!=='true'; menu.setAttribute('aria-expanded',String(open)); nav.classList.toggle('open',open);menu.textContent=open?'Close':'Menu';});
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu';}
nav.querySelectorAll('a').forEach(link => link.addEventListener('click',closeMenu));
document.querySelector('.mobile-order').addEventListener('click',closeMenu);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
document.addEventListener('click',event=>{if(!event.target.closest('.sidebar'))closeMenu();});
function selectItems(items){
 if(!Array.isArray(items)||items.some(item=>!checks.some(c=>c.value===item))) throw new Error('Choose a listed product.');
 checks.forEach(c=>{c.checked=items.includes(c.value)});
 document.querySelector('#order').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 return {selected:checks.filter(c=>c.checked).map(c=>c.value),status:'Order request started. Complete the form and send the email to request an order.'};
}
document.querySelectorAll('.pick').forEach(button=>button.addEventListener('click',()=>{selectItems([...new Set([...checks.filter(c=>c.checked).map(c=>c.value),button.dataset.item])]);if(window.matchMedia('(min-width: 1001px)').matches)document.querySelector(button.dataset.item==='Specific golf ball request'?'#specific-balls':'#customer').focus({preventScroll:true});}));
function createDraft(){const selected=checks.filter(c=>c.checked).map(c=>c.value);if(form.elements.specificBalls.value.trim()&&!selected.includes('Specific golf ball request'))selected.push('Specific golf ball request');return `Hi Maxx,\n\nI'd like to request:\n${selected.map(s=>'- '+s+(s==='Titleist Pro V1 & Pro V1x bag'?' — $4 per ball':'')).join('\n')}\n\nSpecific golf balls requested:\n${form.elements.specificBalls.value.trim()||'Listed selections only'}\n\nQuantities / questions:\n${form.elements.details.value.trim()}\n\nDelivery location and preferred time:\n${form.elements.delivery.value.trim()||'To be arranged'}\n\nPlease confirm availability, prices, and delivery details.\n\nThanks,\n${form.elements.customer.value.trim()}`;}
form.addEventListener('submit',event=>{event.preventDefault();if(!checks.some(c=>c.checked)&&!form.elements.specificBalls.value.trim()){status.textContent='Please choose an item or tell me which specific golf balls you’d like.';checks[0].focus();return;}if(!form.elements.customer.value.trim()||!form.elements.details.value.trim()){status.textContent='Please add your name and quantities or question.';return;}const draft=createDraft();document.querySelector('#email-draft').value=draft;document.querySelector('#draft-fallback').hidden=false;status.textContent='Your draft is ready. Send it from your email app to request an order. If no app opens, copy the text below and email maxxxbutler2000@gmail.com.';window.location.href=`mailto:maxxxbutler2000@gmail.com?subject=${encodeURIComponent('Order request — Maxx’s Lemonade')}&body=${encodeURIComponent(draft)}`;});
document.querySelector('#copy-draft').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#email-draft').value);status.textContent='Order text copied. Paste it into an email to maxxxbutler2000@gmail.com.';}catch{document.querySelector('#email-draft').focus();document.querySelector('#email-draft').select();status.textContent='Select and copy the draft below, then email it to maxxxbutler2000@gmail.com.';}});
const links=[...nav.querySelectorAll('a')];
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){links.forEach(a=>{const active=a.hash==='#'+entry.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}},{rootMargin:'-15% 0px -60% 0px',threshold:0});links.forEach(a=>{const el=document.querySelector(a.hash);if(el)observer.observe(el);});}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'start_order_request',title:'Start an order request',description:'Select products in the visible email order form. Does not send email or confirm an order.',inputSchema:{type:'object',properties:{items:{type:'array',items:{type:'string',enum:checks.map(c=>c.value)},minItems:1}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Array.isArray(input.items)||!input.items.length)throw new Error('Select at least one product.');return selectItems(input.items);}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
